$(document).ready( () =>{


   $(".arrowa").click(()=>{
         $(".conta").addClass("contain")
        $(".conta").addClass("con1").prepend("A hydroplane (or hydro, or thunderboat) is a fast motorboat, where the hull shape is such that at speed, the weight of the boat is supported by planing forces, rather than simple buoyancy. ");
        $(".arrowa").hide(1);
        $(".arrowup").addClass("arup");
        $(".con2").addClass("cont");
            $(".arrowb").click(()=>{
               $(".conta").removeClass("contain")
               $(".conta").removeClass("con1").empty();
               $(".arrowa").show(1);
               $(".arrowup").addClass("arup");
               $(".con2").removeClass("cont");
            })
           $(".arrowc").click(()=>{
               $(".conta").removeClass("contain")
               $(".conta").removeClass("con1").empty();
               $(".arrowa").show(1);
               $(".arrowup").addClass("arup");
               $(".con2").removeClass("cont");
            })
            $(".arrowd").click(()=>{
               $(".conta").removeClass("contain")
               $(".conta").removeClass("con1").empty();
               $(".arrowa").show(1);
               $(".arrowup").addClass("arup");
               $(".con2").removeClass("cont");
            })
    })
    $(".arup1").click(()=>{
        $(".conta").removeClass("contain")
        $(".conta").removeClass("con1").empty();
        $(".arrowa").show(1);
        $(".arrowup").removeClass("arup");
        $(".con2").removeClass("cont");
    })

    $(".arrowb").click(()=>{
        $(".contb").addClass("contain")
        $(".contb").addClass("con2a").prepend(" A key aspect of hydroplanes is that they use the water they are on for lift rather than buoyancy, as well as for propulsion and steering.");
        $(".arrowb").hide(1);
        $(".arrowup").addClass("arup");
        $(".con3").addClass("cont");
           $(".arrowa").click(()=>{
               $(".contb").removeClass("contain")
               $(".contb").removeClass("con2a").empty();
               $(".arrowb").show(1);
               $(".arrowup").addClass("arup");
               $(".con3").removeClass("cont");
            })
            $(".arrowc").click(()=>{
               $(".contb").removeClass("contain")
               $(".contb").removeClass("con2a").empty();
               $(".arrowb").show(1);
               $(".arrowup").addClass("arup");
               $(".con3").removeClass("cont");
            })
            $(".arrowd").click(()=>{
                $(".contb").removeClass("contain")
                $(".contb").removeClass("con2a").empty();
                $(".arrowb").show(1);
                $(".arrowup").addClass("arup");
                $(".con3").removeClass("cont");
            })
    })
    $(".arup2").click(()=>{
        $(".contb").removeClass("contain")
        $(".contb").removeClass("con2a").empty();
        $(".arrowb").show(1);
        $(".arrowup").removeClass("arup");
        $(".con3").removeClass("cont");
    })

 $(".arrowc").click(()=>{
     $(".contc").addClass("contain")
        $(".contc").addClass("con3a").prepend("The water therefore exerts an equal and opposite force upwards.Anim pariatur cliche reprehenderit, enim eiusmod high life .");
        $(".arrowc").hide(1);
        $(".arrowup").addClass("arup");
        $(".con4").addClass("cont");
            $(".arrowa").click(()=>{
                $(".contc").removeClass("contain")
                $(".contc").removeClass("con3a").empty();
                $(".arrowc").show(1);
                $(".arrowup").addClass("arup");
                $(".con4").removeClass("cont");
            })
            $(".arrowb").click(()=>{
                $(".contc").removeClass("contain")
                $(".contc").removeClass("con3a").empty();
                $(".arrowc").show(1);
                $(".arrowup").addClass("arup");
                $(".con4").removeClass("cont");
            })
            $(".arrowd").click(()=>{
                $(".contc").removeClass("contain")
                $(".contc").removeClass("con3a").empty();
                $(".arrowc").show(1);
                $(".arrowup").addClass("arup");
                $(".con4").removeClass("cont");
            })
    })
    $(".arup3").click(()=>{
        $(".contc").removeClass("contain")
        $(".contc").removeClass("con3a").empty();
        $(".arrowc").show(1);
        $(".arrowup").removeClass("arup");
        $(".con4").removeClass("cont");
    })

    $(".arrowd").click(()=>{
        $(".contd").addClass("contain")
        $(".contd").addClass("con4a").prepend("Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,  labore wes anderson cred nesciunt sapiente ea proident.");
        $(".arrowd").hide(1);
        $(".arrowup").addClass("arup");
        $(".con5").addClass("cont");
            $(".arrowa").click(()=>{
               $(".contd").removeClass("contain")
               $(".contd").removeClass("con4a").empty();
               $(".arrowd").show(1);
               $(".arrowup").addClass("arup");
               $(".con5").removeClass("cont");
            })
            $(".arrowb").click(()=>{
               $(".contd").removeClass("contain")
               $(".contd").removeClass("con4a").empty();
               $(".arrowd").show(1);
               $(".arrowup").addClass("arup");
               $(".con5").removeClass("cont");
            })
            $(".arrowc").click(()=>{
                $(".contd").removeClass("contain")
                $(".contd").removeClass("con4a").empty();
                $(".arrowd").show(1);
                $(".arrowup").addClass("arup");
                $(".con5").removeClass("cont");
            })
    })
    $(".arup4").click(()=>{
        $(".contd").removeClass("contain")
        $(".contd").removeClass("con4a").empty();
        $(".arrowd").show(1);
        $(".arrowup").removeClass("arup");
        $(".con5").removeClass("cont");
    })
})